### ISSUE TITLE
Stateful GitHub signup Error page

### ISSUE THREAD

**Issue by SilasReinagel** [sttc/stateful#26]
When I attempt to signup with github from the stateful website, I get the following error page every time.

```
Internal application error (${buildNumber}). 
```

```
date: Tue May 01 16:14:50 UTC 2018
code: NULL
message: java.io.IOException: Failed POST request to https://github.com/login/oauth/access_token?client_id=d20a9be86b7c5af7f923&redirect_uri=http://www.stateful.co/?rexsl-github%3D%26code%3D630d37e1908994060a9e%26rexsl-github%3D&client_secret=c1b7dbca04f995f5898f792a76f405ed227b7e49&code=630d37e1908994060a9e
exception_type: class java.lang.IllegalStateException
request_uri: /
servlet context path: "/"
requested: http://www.stateful.co//trap (GET) at www.stateful.co:80
request: null, -1 bytes
remote: 10.13.219.114:42879 (10.13.219.114)
servlet: "stateful" (API 3.0) at "Apache Tomcat/7.0.34"
headers:
  host: www.stateful.co
  connection: close
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  accept-language: en-US,en;q=0.5
  accept-encoding: gzip, deflate
  referer: http://www.stateful.co/
  cookie: _ga=GA1.2.1675407202.1525130881; _gid=GA1.2.1288662187.1525130881
  upgrade-insecure-requests: 1
  x-request-id: ed0c8e5c-cdca-4bd0-a0ce-f506d18afc24
  x-forwarded-for: 4.14.52.206
  x-forwarded-proto: http
  x-forwarded-port: 80
  via: 1.1 vegur
  connect-time: 0
  x-request-start: 1525191290305
  total-route-time: 0

exception: java.lang.IllegalStateException: java.io.IOException: Failed POST request to https://github.com/login/oauth/access_token?client_id=d20a9be86b7c5af7f923&redirect_uri=http://www.stateful.co/?rexsl-github%3D%26code%3D630d37e1908994060a9e%26rexsl-github%3D&client_secret=c1b7dbca04f995f5898f792a76f405ed227b7e49&code=630d37e1908994060a9e
	at com.rexsl.page.auth.AuthInset.ofProviders(AuthInset.java:243)
	at com.rexsl.page.auth.AuthInset.identity_aroundBody6(AuthInset.java:140)
	at com.rexsl.page.auth.AuthInset$AjcClosure7.run(AuthInset.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.auth.AuthInset.identity_aroundBody8(AuthInset.java:140)
	at com.rexsl.page.auth.AuthInset$AjcClosure9.run(AuthInset.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:302)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:147)
	at com.rexsl.page.auth.AuthInset.identity(AuthInset.java:140)
	at co.stateful.rest.BaseRs$3.render(BaseRs.java:140)
	at com.rexsl.page.BasePage.render_aroundBody2(BasePage.java:175)
	at com.rexsl.page.BasePage$AjcClosure3.run(BasePage.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.BasePage.render(BasePage.java:168)
	at co.stateful.rest.IndexRs.index(IndexRs.java:57)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at com.rexsl.core.RestfulServlet.service_aroundBody2(RestfulServlet.java:175)
	at com.rexsl.core.RestfulServlet$AjcClosure3.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.RestfulServlet.service_aroundBody4(RestfulServlet.java:174)
	at com.rexsl.core.RestfulServlet$AjcClosure5.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.RestfulServlet.service(RestfulServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.rexsl.core.XsltFilter.filter(XsltFilter.java:170)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody2(XsltFilter.java:139)
	at com.rexsl.core.XsltFilter$AjcClosure3.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody4(XsltFilter.java:137)
	at com.rexsl.core.XsltFilter$AjcClosure5.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:137)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed POST request to https://github.com/login/oauth/access_token?client_id=d20a9be86b7c5af7f923&redirect_uri=http://www.stateful.co/?rexsl-github%3D%26code%3D630d37e1908994060a9e%26rexsl-github%3D&client_secret=c1b7dbca04f995f5898f792a76f405ed227b7e49&code=630d37e1908994060a9e
	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:127)
	at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:336)
	at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:251)
	at com.rexsl.page.auth.Github.token(Github.java:165)
	at com.rexsl.page.auth.Github.identity_aroundBody0(Github.java:117)
	at com.rexsl.page.auth.Github$AjcClosure1.run(Github.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.auth.Github.identity(Github.java:103)
	at com.rexsl.page.auth.AuthInset.ofProviders(AuthInset.java:241)
	... 78 more
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1989)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1096)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1093)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:111)
	... 89 more
```

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) I'm not managing this repo, remove the [webhook](https://github.com/sttc/stateful/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `sttc/stateful` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)
