### ISSUE TITLE
Is there any chance to get fully working build?

### ISSUE THREAD

**Issue by artem-korolev** [sttc/stateful#34]
Hi,

I guess you know that Travis CI gives failure for all of recent builds. I was trying to build locally with openjdk 11 and getting same result.
With openjdk-8 I'm getting totally different result:

```
	at com.jcabi.xml.DomParser.<init>(DomParser.java:91)
	at com.jcabi.xml.XMLDocument.<init>(XMLDocument.java:159)
	at com.jcabi.matchers.StringSource.<init>(StringSource.java:67)
	at com.jcabi.matchers.XhtmlMatchers.xhtml(XhtmlMatchers.java:113)
	at com.jcabi.matchers.XPathMatcher.matchesSafely(XPathMatcher.java:75)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at com.jcabi.http.response.XmlResponse.assertXPath(XmlResponse.java:134)
	at com.jcabi.w3c.DefaultHtmlValidator.validate(DefaultHtmlValidator.java:74)
	at com.jcabi.matchers.W3CValidatorMatcher.matchesSafely(W3CValidatorMatcher.java:78)
	at com.jcabi.matchers.W3CValidatorMatcher.matchesSafely(W3CValidatorMatcher.java:49)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at com.jcabi.http.response.RestResponse.assertBody(RestResponse.java:146)
	at co.stateful.rest.IndexRsITCase.rendersValidHtml(IndexRsITCase.java:127)
Running co.stateful.core.DyCounterITCase
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.088 sec - in co.stateful.core.DyCounterITCase
Running co.stateful.rest.ErrorRsITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in co.stateful.rest.ErrorRsITCase
Running co.stateful.core.DyCountersITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.473 sec - in co.stateful.core.DyCountersITCase
Running co.stateful.core.DefaultUserITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.491 sec - in co.stateful.core.DefaultUserITCase
Results :
Tests in error: 
  CountersRsITCase.rendersValidHtml:103 » IllegalArgument Doesn't look like XML:...
  IndexRsITCase.rendersValidHtml:127 » IllegalArgument Doesn't look like XML: 'S...
Tests run: 13, Failures: 0, Errors: 2, Skipped: 1
```

[co.stateful.rest.CountersRsITCase.txt](https://github.com/sttc/stateful/files/7318044/co.stateful.rest.CountersRsITCase.txt)
[co.stateful.rest.IndexRsITCase.txt](https://github.com/sttc/stateful/files/7318047/co.stateful.rest.IndexRsITCase.txt)

**Comment by yegor256** [comment]
@artem-korolev it works now, see GitHub Action

**Comment by artem-korolev** [comment]
that's great! thank you!  ....even after almost 2 years :)
